name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies with pipenv
      run: |
        pipenv install --dev

    - name: Lint with flake8
      run: |
        pipenv run flake8 src tests --count --select=E9,F63,F7,F82 --show-source --statistics
        pipenv run flake8 src tests --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Generate coverage report
      run: |
        pipenv run pytest --cov-report xml:coverage.xml --cov=src tests/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        name: codecov-umbrella
        fail_ci_if_error: true
